version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
artifacts:
- path: FMBot_Discord\FMBot_Discord\bin\$(configuration)
  name: BinaryRelease
- path: BinaryFiles
  name: BinaryFiles
- path: FMBot_Discord\FMBot_Discord\config.json
  name: BinaryConfig

